config/routes.rb
Rails.application.routes.draw do
  get 'cart/index'
  get 'products/index'
  get 'products/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'products#index'
  post '/' => 'cart#clear_cart', as: :clear_cart

  get '/about' => 'about#show', as: :about

  get '/contact' => 'contact#show', as: :contact

  get '/products' => 'products#index', as: :products
  get '/product/:id' => 'products#show', as: :product, id: /\d+/

  post '/cart/add/:id' => 'cart#add_to_cart', as: :add_to_cart, id: /\d+/
  post '/cart/remove/:id' => 'cart#remove_from_cart', as: :remove_from_cart, id: /\d+/
  get '/cart' => 'cart#index', as: :cart

  post '/order/new' => 'cart#create_order_for_customer', as: :customers
  post '/order/confirm' => 'cart#confirm_order', as: :confirm_cart
  get 'order/new' => 'cart#index'
end

app/models/about.rb
class About < ActiveRecord::Base
  validates :title, :description, presence: true
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :description, presence: true

  has_many :products
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :description, :phone, :email, :address, presence: true
  validates :email, format: { with:  /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\Z/ }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :first_name, :last_name, :address, :city, :postal_code, :email, :province_id,
            presence: true
  validates :email, format: { with:  /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\Z/ }
  validates :postal_code, format: { with: /\A([ABCEGHJKLMNPRSTVXY]\d){3}\Z/ }

  belongs_to :province
  has_many :orders

  has_many :line_items, through: :orders

  def tax_rate
    province.safe_gst + province.safe_pst + province.safe_hst
  end

  def make_order(products, flash, session)
    flash[:notice], flash[:code] = ['There was an error creating your order! Please try again.', 1]

    # Saving customer
    return false unless save

    # Creating order
    order = Order.create_order(itself)
    order.save

    # Creating line items
    products.each do |product|
      LineItem.create_line_item(order, product, 1).save
    end

    flash[:notice], flash[:code] = ['Order successfully created!', 0]
    session[:cart] = []
    true
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  validates :quantity, :price, :order_id, :product_id, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  belongs_to :order
  belongs_to :product

  has_one :customer, through: :order

  def self.create_line_item(order, product, quantity)
    line_item = LineItem.new

    line_item.quantity = quantity
    line_item.price = product.price
    line_item.order = order
    line_item.product = product

    line_item
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :status, :customer_id, presence: true
  validates :pst, :gst, :hst, numericality: true, allow_nil: true
  validates :status, inclusion: { in: %w( outstanding paid shipped ) }

  belongs_to :customer
  has_many :line_items

  has_many :products, through: :line_items

  def self.create_order(customer)
    order = Order.new

    order.status = 'outstanding'
    order.pst = customer.province.pst
    order.gst = customer.province.gst
    order.hst = customer.province.hst
    order.customer = customer

    order
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :description, :price, :quantity, :category_id, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  belongs_to :category
  has_many :line_items

  has_many :orders, through: :line_items

  mount_uploader :image, ImageUploader

  def self.filter_by_sale(products, sale)
    return products unless sale == 'on'

    products.where!("price LIKE '%.98'")
  end

  def self.filter_by_new(products, new)
    return products unless new == 'on'

    products.where!('created_at > :date', date: 3.week.ago)
  end

  def self.filter_by_category(products, category_id)
    return products unless category_id
    return products if category_id == 'all'

    products.where!(category_id: category_id)
  end

  def self.filter_by_query(products, query)
    return products unless query

    products.where!("name LIKE '%#{query}%' OR description LIKE '%#{query}%'")
  end

  def self.filter(products, params)
    filter_by_category(products, params[:category])
    filter_by_query(products, params[:query])
    filter_by_sale(products, params[:sale])
    filter_by_new(products, params[:new])
  end
end

app/models/province.rb
class Province < ActiveRecord::Base
  validates :name, presence: true
  validates :pst, :gst, :hst, numericality: { greater_than_or_equal_to: 0.01 }, allow_nil: true

  has_many :customer

  def safe_gst
    gst || 0
  end

  def safe_pst
    pst || 0
  end

  def safe_hst
    hst || 0
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
    @about = About.first ||
             OpenStruct.new(title: 'No content',
                            description: 'Please add content to this about page')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :setup_cart

  def setup_cart
    session[:cart] ||= []
  end

  def customer_from_flash
    Customer.new(flash[:customer])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :cart_variables, only: [:index, :create_order_for_customer]

  def index
    flash[:customer] = @customer = customer_from_flash
  end

  def create_order_for_customer
    @customer = Customer.new(customer_params)
    return redirect_to :cart unless session[:cart].any?

    if @customer.valid?
      @taxes = @subtotal * @customer.tax_rate
      @total = @subtotal + @taxes
      flash[:customer] = @customer
    else
      render :index
    end
  end

  def confirm_order
    products = session[:cart].map { |e| Product.find(e) }
    customer = customer_from_flash

    customer.make_order(products, flash, session)

    redirect_to root_path
  end

  def add_to_cart
    session[:cart] << params[:id]
    session[:cart].uniq!

    redirect_to :back
  end

  def remove_from_cart
    session[:cart] -= [params[:id]]

    redirect_to :back
  end

  def clear_cart
    session[:cart] = []
    flash.discard

    redirect_to root_path
  end

  private

  def customer_params
    params.require('customer')
      .permit(:first_name, :last_name, :address, :city, :postal_code, :email, :province_id)
  end

  def cart_variables
    @products = session[:cart].map { |id| Product.find(id) }
    @subtotal = @products.reduce(0) { |a, e|  a + e.price }
    @provinces = Province.all
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
    @contact = Contact.first ||
               OpenStruct.new(description: 'No content',
                              phone: 'Please add a phone number',
                              email: 'Please add and email',
                              address: 'Please add an address')
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.filter(Product.all, params).order(:name).page(params[:page]).per(8)
    @categories = Category.order(:name)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/about/show.html.erb
<div class="container">
  <h1><%= @about.title %></h1>
  <%= simple_format @about.description %>
</div>

app/views/cart/_list.html.erb
<table class="cart">
  <thead>
  <tr>
    <th>Image</th>
    <th>Item</th>
    <th>Price</th>
    <th>Operation</th>
  </tr>
  </thead>
  <tbody>
  <% if products.length == 0 %>
      <tr>
        <td colspan="4" style="color: #AAA">No items in cart</td>
      </tr>
  <% end %>
  <% products.each do |product| %>
      <tr>
        <td><%= image_tag product.image.thumb.url %></td>
        <td><%= product.name %></td>
        <td>CND <%= number_to_currency(product.price) %></td>
        <td>
          <%= link_to remove_from_cart_path(product.id), method: :post, class: 'button', data: {confirm: "Remove #{product.name}?"} do %>
              <span class="fa fa-trash"></span>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td colspan="4"><strong>Total Items:</strong> <span><%= products.length %></span></td>
  </tr>
  <tr>
    <td colspan="4"><strong>Subtotal:</strong> <span><%= number_to_currency(subtotal) %></span></td>
  </tr>
  <% if @taxes %>
    <tr>
      <td colspan="4"><strong>Taxes:</strong> <span><%= number_to_currency(taxes) %></span></td>
    </tr>
    <tr>
      <td colspan="4"><strong>Grand Total:</strong> <span><%= number_to_currency(total) %></span></td>
    </tr>
  <% end %>
  </tfoot>
</table>

app/views/cart/create_order_for_customer.html.erb
<div class="container">
  <h1>Confirm Order</h1>
  <%= render partial: 'cart/list', locals: { products: @products, subtotal: @subtotal, taxes: @taxes, total: @total } %>

  <section class="info">
    <h2>Order Information</h2>
    <ul>
      <li>
        <span class="label">Name:</span>
        <%= "#{@customer.first_name} #{@customer.last_name}" %>
      </li>
      <li>
        <span class="label">Province:</span>
        <%= @customer.province.name %>
      </li>
      <li>
        <span class="label">City:</span>
        <%= @customer.city %>
      </li>
      <li>
        <span class="label">Address:</span>
        <%= @customer.address %>
      </li>
      <li>
        <span class="label">Postal Code:</span>
        <%= @customer.postal_code %>
      </li>
      <li>
        <span class="label">Email:</span>
        <%= @customer.email %>
      </li>
    </ul>
  </section>

  <p class="confirm">
    <%= link_to confirm_cart_path, class: 'button', method: :post do %>
      <span class="fa fa-check"></span> Confirm
    <% end %>

    <%= link_to cart_path, class: 'button' do %>
        <span class="fa fa-edit"></span> Edit
    <% end %>

    <%= link_to clear_cart_path, class: 'button', method: :post do %>
        <span class="fa fa-close"></span> Cancel
    <% end %>
  </p>
</div>

app/views/cart/index.html.erb
<div class="container">
  <h1>Cart Items</h1>

  <%= render partial: 'cart/list', locals: { products: @products, subtotal: @subtotal } %>

  <% if @customer.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@customer.errors.count, 'error') %>:</h3>

        <ul>
          <% @customer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <%= form_for(@customer, html: { class: 'order' }) do |f| %>
    <fieldset>
      <legend>Order Information</legend>
      <ul>
        <li>
          <%= f.label :first_name %>
          <%= f.text_field :first_name, required: true, placeholder: 'John' %>
        </li>
        <li>
          <%= f.label :last_name %>
          <%= f.text_field :last_name, required: true, placeholder: 'Smith' %>
        </li>
        <li>
          <%= f.label :province_id %>
          <select id="customer_province_id" name="customer[province_id]" required="required">
            <option value="">Please select a province</option>
            <% @provinces.each do |province| %>
                <option value="<%= province.id %>" <%= 'selected' if province == @customer.province %>><%= province.name %></option>
            <% end %>
          </select>
        </li>
        <li>
          <%= f.label :city %>
          <%= f.text_field :city, required: true, placeholder: 'Winnipeg' %>
        </li>
        <li>
          <%= f.label :address %>
          <%= f.text_field :address, required: true, placeholder: 'Box 770' %>
        </li>
        <li>
          <%= f.label :postal_code %>
          <%= f.text_field :postal_code, required: true, placeholder: 'R0A0T0' %>
          <!-- , pattern: '^([ABCEGHJKLMNPRSTVXY]\d){3}$' -->
        </li>
        <li>
          <%= f.label :email %>
          <%= email_field 'customer', :email, required: true, placeholder: 'fake@example.com' %>
        </li>
        <li>
          <%= f.submit 'Checkout', disabled: !session[:cart].any? %>
        </li>
      </ul>
    </fieldset>
  <% end %>
</div>

app/views/contact/show.html.erb
<div class="container">
  <h1>Contact</h1>
  <%= simple_format @contact.description %>
  <ul class="contact-info">
    <li><span>Phone: </span><%= @contact.phone %></li>
    <li><span>E-Mail: </span><%= @contact.email %></li>
    <li>
      <span>Address:</span>
      <br />
      <%= simple_format @contact.address %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaseWayz ~ <%= params[:controller].capitalize %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
    <nav class="global">

        <ul>
          <li class="float">
            <span class="fa fa-shopping-cart"></span>
            <%= link_to(cart_path) do %>
                <span class="cart"><%= session[:cart].length %></span>
            <% end %>
          </li>
          <li>
            <%= link_to(root_path) do %>
                <span class="logo"><span>Case</span>Wayz</span>
            <% end %>
          </li>
          <li>
            <%= link_to(root_path) do %>
                <span class="fa fa-home"></span> Home
            <% end %>
          </li>
          <li>
            <%= link_to(about_path) do %>
                <span class="fa fa-question"></span> About
            <% end %>
          </li>
          <li>
            <%= link_to(contact_path) do %>
                <span class="fa fa-phone"></span> Contact
            <% end %>
          </li>
          <li>
            <%= link_to(products_path) do %>
                <span class="fa fa-mobile"></span> Products
            <% end %>
          </li>
        </ul>
    </nav>

    <%= yield %>
</body>
</html>

app/views/products/_product.html.erb
<div class="item">
  <% if product.price.to_s.end_with?('.98') %>
    <p class="sale"><span>On Sale</span></p>
  <% end %>
  <p class="image">
    <%= link_to(product) do %>
        <%= image_tag product.image.list_display.url, alt: product.name %>
    <% end %>
  </p>
  <%= simple_format truncate(product.description, length: 95) %>
  <p class="price">
    CDN <%= number_to_currency(product.price) %>
  </p>
</div>

app/views/products/_search.html.erb
<div class="container">
  <form class="search" method="GET">
    <fieldset>
      <ul>
        <li>
          <label for="query">Search:</label>
          <input id="query" name="query" type="text" />
        </li>
        <li>
          <label for="category">Category:</label>
          <select id="category" name="category">
            <option value="all">All</option>
            <% @categories.each do |category| %>
                <option value="<%= category.id %>" <%= 'selected' if params[:category] == category.id.to_s %>><%= category.name %></option>
            <% end %>
          </select>
        </li>
        <li class="bottom"><input id="sale" name="sale" type="checkbox" <%= 'checked' if params[:sale] == 'on' %> /> <label for="sale" class="check">On Sale</label></li>
        <li class="bottom"><input id="new" name="new" type="checkbox" <%= 'checked' if params[:new] == 'on' %> /> <label for="new" class="check">New Items</label></li>
        <li class="bottom"><button type="submit">Go</button></li>
      </ul>
    </fieldset>
  </form>
</div>

app/views/products/index.html.erb
<% if flash[:notice] %>
    <div class="notice <%= flash[:code] == 0 ? 'success' : 'error' %>">
      <p><%= flash[:notice] %></p>
    </div>
<% end %>

<%= render 'search' %>

<div class="container">
  <div class="products">
    <%= render @products %>
  </div>
  <section class="pages">
    <%= paginate @products %>
    <%= page_entries_info @products %>
  </section>
</div>

app/views/products/show.html.erb
<div class="single-item container">
  <h1><%= @product.name %></h1>
  <p class="image">
    <span class="price">CND <%= number_to_currency @product.price %></span>
    <br />
    <span class="quantity"><strong>Quantity: </strong> <%= @product.quantity %></span>
    <br />
    <%= image_tag @product.image.url, alt: @product.name %>
    <br />
    <%= link_to(add_to_cart_path(@product), method: :post, class: 'button') do %>
        <span class="fa fa-plus-circle"></span> Add to Cart
    <% end %>
  </p>
  <p class="sep">Details</p>
  <section class="details">
    <h2>Description</h2>
    <%= simple_format @product.description %>
  </section>
  <span class="hidden" id="price"><%= @product.price %></span>
</div>